### ISSUE TITLE
Set source as the default branch

### ISSUE THREAD

**Issue by mgarciaisaia** [butterproject/butterproject.github.io#19]
As [per the docs](https://help.github.com/articles/user-organization-and-project-pages/#user--organization-pages), GH:Pages sites get built from the `master` branch, it doesn't mean it has to be the main branch of the repository.

For encouraging contributions, it would be best to set `source` as [the default branch](https://github.com/butterproject/butterproject.github.io/settings/branches), so newcomers actually fix the corresponding sources and not the generated site.

**Comment by MrAdder** [comment]
:+1: will be Discussing that when I can get ahold of xaiki or insertcoin

**Comment by xaiki** [comment]
done !
