### ISSUE TITLE
Butter logo

### ISSUE THREAD

**Issue by giacomocerquone** [butterproject/butterproject.github.io#26]
So do you have a new logo? For what I can see you're using two different logos:
This:
![butter logo](http://i61.tinypic.com/4hfehs.png)
This one:
![butter logo 2](http://i60.tinypic.com/2m6l7py.png)
and in a section of the website there still be a popcorntime logo.

I think we absolutely should choose one logo to use everywhere. And if you don't like those, we can always open a contest where designers make suggestions.

**Comment by xaiki** [comment]
where do you see the second logo ?

**Comment by giacomocerquone** [comment]
in the footer of the website...

**Comment by giacomocerquone** [comment]
Now I see. There are two files with the same name but different extension. The footer-logo.png is the first one I posted, the footer-logo.svg, is the second one. Shouldn't they be the same?

**Comment by se-bastiaan** [comment]
@xaiki fixed, svg was text not outlines. just needs update on the other branch

**Comment by giacomocerquone** [comment]
Perfect, so I can close this.
