### ISSUE TITLE
Responsiveness problems

### ISSUE THREAD

**Issue by giacomocerquone** [butterproject/butterproject.github.io#35]
So this website have two main problems when is rendered on a smartphone browser (I've a Nexus 5 but actually you have small problems with links with displays from 450px to 600px wide and big problems with links and unused space with displays under 450px wide).
Here screenshots of the two problems marked by red rectangles:
![immagine](https://cloud.githubusercontent.com/assets/9303791/10773198/59ecf5ce-7cfa-11e5-9c5c-7a94e69a96dc.jpg)
![5bad89dc-7cfa-11e5-96f6-de4a7aad4e98](https://cloud.githubusercontent.com/assets/9303791/10774562/31caf908-7d02-11e5-8981-a010bb3791fb.jpg)

I'm doing a PR on the source branch to fix this.

**Comment by MrAdder** [comment]
Merged will push to production shortly
