### ISSUE TITLE
http://butterproject.org/ mentions popcorntime.io

### ISSUE THREAD

**Issue by rom1504** [butterproject/butterproject.github.io#37]
I'm not sure what are your plans exactly, but it seems like popcorntime.io will stay down, so it might be a good idea to update http://butterproject.org/ to reflect that.

**Comment by hadim** [comment]
PR are welcome !

**Comment by rom1504** [comment]
That's not how issues work.

**Comment by hadim** [comment]
Better to ask the question in the forum then : http://discuss.butterproject.org/
