### ISSUE TITLE
Claim of "copyright free" is inaccurate

### ISSUE THREAD

**Issue by perey** [butterproject/butterproject.github.io#50]
In the [FAQ](https://github.com/butterproject/butterproject.github.io/blob/059949544f1bb61f56b61564fc33fb75a5f07f72/src/templates/content/faq.ejs#L10), the following claim is made: "100% copyright free? Yes."

This indicates that all content available through Butter is public domain, i.e. "free of copyright". As the context (and mention of CC licenses) makes clear, this is not correct. It seems that what is meant is "100% free of copyright **violations**".

A better statement might be "100% free and legal".

**Comment by xaiki** [comment]
that's an interesting point. updated, thanks for the catch.
